# Generated by Django 4.2.9 on 2024-01-29 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0004_attendance_break_userprofile_delete_attendencedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendencedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_hours', models.CharField(max_length=100)),
                ('total_break', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('end', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(auto_now=True)),
                ('now_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='break',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
